# -*- coding: utf-8 -*-
"""Process mining_Ex-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJBJqG4R7a5rMstdVBpMqb6AdzuBWbsO
"""

class PetriNet():

    def __init__(self):
        self.places = {}
        self.transitions = {}

    def add_place(self, name, id=0):
        self.places[name] = id

    def add_transition(self, name, id):
        if id not in self.transitions:
          self.transitions[id] = {"name": name,"inputs": [], "outputs": []}

    def add_edge(self, source, target):
        if source in self.places and target in self.transitions:
          self.transitions[target]["inputs"].append(source)

        elif source in self.transitions and target in self.places:
          self.transitions[source]["outputs"].append(target)

        return self
    def get_tokens(self, place):
        return self.places.get(place, None)

    def is_enabled(self, transition):
        for place in self.transitions[transition]["inputs"]:
          if self.places[place] <= 0:
            return False
        return True

    def add_marking(self, place, id = 1):
        if place in self.places:
          self.places[place] += id


    def fire_transition(self, transition):
        if not self.is_enabled(transition):

          return False

        for place in self.transitions[transition]["inputs"]:
          self.places[place] -=1

        for place in self.transitions[transition]["outputs"]:
          self.places[place] +=1


        return True